### ISSUE TITLE
Run template commands

### ISSUE THREAD

**Issue by xilaraux** [open-cli-tools/concurrently#148]
Hello.

I think there are some mistakes in the DOCS, because this stuff has never worked for me.

```
concurrently "npm:watch-*"

# Equivalent to:
concurrently -n js,css,node "npm run watch-js" "npm run watch-css" "npm run watch-node"

# Any name provided for the wildcard command will be used as a prefix to the wildcard
# part of the script name:
concurrently -n w: npm:watch-*

# Equivalent to:
concurrently -n w:js,w:css,w:node "npm run watch-js" "npm run watch-css" "npm run watch-node"
```

Thx.

**Comment by gustavohenke** [comment]
Can clarify yourself?
What is not working for you? Do you get any errors? What is the output?

Please provide as much details as you can.

**Comment by mastilver** [comment]
I think I'm having the same problem with names

It use to be that the wildcard was the name suffix:
https://github.com/kimmobrunfeldt/concurrently/pull/140/files#diff-7da21ee57c9bb94e0425929d61b38d5eR128
https://github.com/kimmobrunfeldt/concurrently/pull/140/files#diff-7da21ee57c9bb94e0425929d61b38d5eR154

whereas right now the name is the full command name

-------
So
`concurrently "npm:watch-*"`
is equivalent to
`concurrently -n watch-js,watch-css,watch-node "npm run watch-js" "npm run watch-css" "npm run watch-node"`

and
`concurrently -n w: npm:watch-*`
is equivalent to
`concurrently -n watch-js,watch-css,watch-node "npm run watch-js" "npm run watch-css" "npm run watch-node"`

notice they are both the same as it's not looking at the name anymore


I will try to have a look at the code and submit a PR

**Comment by mikeharder** [comment]
I'm hitting the same issue, and I prefer the behavior in #165 to the current behavior.
