### ISSUE TITLE
Stagger (delay between starting)

### ISSUE THREAD

**Issue by aubelsb2** [open-cli-tools/concurrently#201]
In some cases you want to have a small period of tine between each process you're starting. Ie launch them with 1 second between or some such.. Is there a way to do that?

**Comment by gustavohenke** [comment]
Not through the CLI, but maybe with the API.

```js
const commands = [
	'npm run server',
	'npm run watch:js',
	'npm run watch:css'
].map((command, i) => {
	// Will wait 0s before the first command, then 1s before the second, and so on
	return `sleep ${i} && ${command}`;
});

const concurrently = require('concurrently');
concurrently(commands).then(success, failure);
```

What's your use case? I may be able to provide a few other ideas.

**Comment by aubelsb2** [comment]
It's changed as i have other issues along the same lines. But basically it was due to a bad seed. So all the temporary filenames were the same.

**Comment by KaranGauswami** [comment]
I want to run `tsc --watch` and `nodemon dist\index.js` together, but i want to wait before typescript compiler compiles the code , any ideas ?

**Comment by cben** [comment]
Does `tsc --watch` produce a specific file / listen on a port?  For wait-until-a-backend-starts scenarios I'm using https://github.com/jeffbski/wait-on.
```
concurrently "./backend" "yarn wait-on http://localhost:8001/ && yarn e2e-test
```

@KaranGauswami for tsc, see https://github.com/microsoft/TypeScript/issues/12996 and the dedicated https://www.npmjs.com/package/tsc-watch

**Comment by KaranGauswami** [comment]
Thanks @cben .

**Comment by gustavohenke** [comment]
Closing this issue for now -- but using `wait-on`, like suggested above, is a great idea and much less likely to cause flakiness in your flows.
