### ISSUE TITLE
Allow the use of other signal on kill-others

### ISSUE THREAD

**Issue by Nox-404** [open-cli-tools/concurrently#202]
Hello,
Is it possible to choose which signal is sent when kill-others is triggered ?

When on windows, the SIGTERM signal cannot be handled, preventing us to release some resources properly.

**Comment by gustavohenke** [comment]
Hello!
Not really possible. Current set includes `SIGINT`, `SIGTERM` and `SIGHUP`, which are all Unix based.

It's probably worth looking at adapting those to Windows.
Do you have suggestions on how to do this?

**Comment by Nox-404** [comment]
Well `SIGINT` works, so you could add another option to use that signal for `kill-others` and the user can implement to respond to it as needed.
Not really a good solution but at least that gives some control

**Comment by samuelpetroline** [comment]
If i'm not mistaken, concurrently uses `tree-kill` for handling process exit. As it is stated in their docs, it is possible to send another signal:

```javascript
var kill = require('tree-kill');
kill(1, 'SIGKILL');
```

Maybe this could be used somehow?

**Comment by gustavohenke** [comment]
`SIGKILL` should be force quit, which I'm pretty sure doesn't give time for the process to respond and thus close its children gracefully 😐

**Comment by Nox-404** [comment]
It would be great to just be able to choose while keeping the current behavior by default. And yes SIGKILL cannot be handled, since it terminates the program brutally :) but useful to some use cases I guess
