### ISSUE TITLE
Get commands/processes list OR How to kill some concurrently process from outside

### ISSUE THREAD

**Issue by SARFEX** [open-cli-tools/concurrently#209]
Subj

Actually, I want to restart a single process by "killing" it, from the same place, where I have initiated concurrently.
How can I do this?

**Comment by gustavohenke** [comment]
Hi @SARFEX,
One such way is to grab the PID off of the output. It's not great, I know!

**Comment by gustavohenke** [comment]
An idea I have is to expand the returned value of the programmatic API to be something like this:

```
const commands = concurrently(['echo foo', 'echo bar'], options);
commands.result // promise that resolves/rejects according to the success condition of the options
commands.pids // an array of PIDs

// could have more useful stuff
```

WDYT? This would be a major/breaking change then.

**Comment by aalimovs** [comment]
@gustavohenke what about expanding the input handling functionality and adding ability to restart a process? E.g. `srv:restart` `0:restart`. There could be a conflict where you might actually want to pass `restart` as an input to the process, we could escape it with `srv:!restart`, and use it for any future commands too

**Comment by alexweininger** [comment]
This would be really useful for me. I'd be willing to help with this feature. We could potentially avoid a breaking change by adding a flag or a callback.

But if the breaking change is too large, is there another tool like concurrently that can expose the pids?

**Comment by gustavohenke** [comment]
Happy new year! This is now out in [`v7.0.0`](https://github.com/open-cli-tools/concurrently/releases/tag/v7.0.0).
