### ISSUE TITLE
Wildcard naming is verbose and doesn't match docs

### ISSUE THREAD

**Issue by transitive-bullshit** [open-cli-tools/concurrently#211]
Same issue as #148 though I will include a better description & repro case.

**Problem**: if you use the `npm:` or `yarn:` wildcard syntax, the docs say we should get only the shortened wildcard portion of the commands as labels, but in reality this is broken and we get the full, verbose version of the commands, including the non-wildcard prefix.

Here is a bare-bones [repro example](https://github.com/transitive-bullshit/concurrently-bug-repro). It just uses the wildcard syntax to call `echo.js` which just logs its argv once a second.

Here is the current output:

```
$ concurrently yarn:start-*
$ node echo.js foo
$ node echo.js bar
[start-foo] foo
[start-bar] bar
[start-bar] bar
[start-foo] foo
[start-bar] bar
[start-foo] foo
```

Here is the expected and desired output:

```
$ concurrently yarn:start-*
$ node echo.js foo
$ node echo.js bar
[foo] foo
[bar] bar
[bar] bar
[foo] foo
[bar] bar
[foo] foo
```

This clearly does the opposite of what was intended and described in the project's readme.

#165 looks like the correct fix, but it is out of date. @gustavohenke if you'll accept an updated PR, I'm happy to resolve this for you.

Thanks!

**Comment by gustavohenke** [comment]
> if you'll accept an updated PR, I'm happy to resolve this for you.

Sure thing! ❤️

**Comment by AmmarArnt** [comment]
Did this get broken in a newer release? I am running version 7.1.0 and I get the pre-wildcard description in the terminal:`[_start-*subscriptions]`
