### ISSUE TITLE
prefix colors doesn't work in v5.2.0

### ISSUE THREAD

**Issue by kshitijk83** [open-cli-tools/concurrently#220]
`concurrently --names \"front, back\" --prefix \"[{name}]\" --prefix-colors \"bgCyan.reset.bold,bgGreen.reset.bold\" \"npm run dev:front --silent\" \"npm run dev:back --silent\"`
Here's my command it works for v3.5.1 but not in latest version

**Comment by gustavohenke** [comment]
Since it's been a while, I'll close this issue.
If you still have this problem against the latest version, please open a new issue -- it'd be good to understand more about the OS, environment variables, node version, etc.
