### ISSUE TITLE
New organisation / owner for the repository

### ISSUE THREAD

**Issue by kimmobrunfeldt** [open-cli-tools/concurrently#222]
How do you feel about moving this repository into its own organization? I haven't had time to contribute lately and feel like just being a blocker for some CI etc setup. What do you think @gustavohenke ?

**Comment by gustavohenke** [comment]
> How do you feel about moving this repository into its own organization? I haven't had time to contribute lately

I really don't mind changing much 🤷 I also don't have much time to respond/fix issues these days.

If you feel strongly about it, then yeah maybe an org is better.

> feel like just being a blocker for some CI etc setup

are you? 🤔

**Comment by kimmobrunfeldt** [comment]
Ok thanks for the comments. Let's see if some other parties would benefit from the organisation changes. We can keep things as is and move to a new org if more contributors are interested. 

Probably not a huge blocker now but just thinking about future: if I don't check this repo for a few months and critical updates are needed.

**Comment by cjbarth** [comment]
In that case, why not just put a banner on this project directing people to [npm-run-all](https://github.com/mysticatea/npm-run-all/issues/10)?

**Comment by tfrijsewijk** [comment]
@cjbarth Could you explain why I should install npm-run-all over concurrently? One the indicators I use is the last published date, npm-run-all hasn't been updated in 2 years, concurrently 5 days at the time of writing..

I was about to use concurrently for a project, and then I saw this issue

**Comment by cjbarth** [comment]
@tfrijsewijk I was more commenting on how the maintainer of this project would seemingly prefer not to maintain it. I found another thread, which I linked to in my previous comment, which discusses this very problem. That thread includes more options that just concurrently and npm-run-all.

**Comment by gustavohenke** [comment]
👋 @kimmobrunfeldt, it may be a good time to think about the handover.

I'm not a fan of changing URLs (despite GitHub handling the redirects nicely), but would like to tune some settings - which unfortunately GitHub doesn't let me unless I'm the owner 😕

**Comment by akauppi** [comment]
If this is the most urgent need for maintaining concurrently, would you consider pinning it to get more publicity?

**Comment by kimmobrunfeldt** [comment]
I moved the repo under a new organisation to get things moving immediately. The links etc will be updated once the owner details are locked.
