### ISSUE TITLE
Per command spawn options

### ISSUE THREAD

**Issue by zuffik** [open-cli-tools/concurrently#223]
Is there any way to provide spawn options for each command? For example _cwd_, _stdio_, etc.

**Comment by gustavohenke** [comment]
It wasn't possible back then, but nowadays you can specify cwd and environment per command using the programmatic API.

```
concurrently([
	{ command: 'echo $HELLO', env: { HELLO: 'hello world' } },
	{ command: 'pwd', cwd: '~/Downloads' },
]);
``
`
