### ISSUE TITLE
Unexpected color changes in Angular commands' output

### ISSUE THREAD

**Issue by peruukki** [open-cli-tools/concurrently#238]
We use Concurrently to run various commands in an Angular project. After upgrading to Angular 10, we are seeing unexpected color changes in various Angular commands' output, even in the middle of output lines.

Here is the output of an `ng serve` command when run directly on the command line:
![ng-serve-directly](https://user-images.githubusercontent.com/1781172/89648279-a6fe5a00-d8c7-11ea-943b-b74b8e5c267f.png)

Here is the same when run (prefixed "admin") via Concurrently:
![ng-serve-via-concurrently](https://user-images.githubusercontent.com/1781172/89648339-c0070b00-d8c7-11ea-81db-dcf9005951f7.png)

Should the output colors be the same? In any case, any ideas what might cause this behavior? The colors have never been the same for us, but these kinds of color changes (white to green) only started after we upgraded Angular.

We are using Concurrently programmatically if that makes a difference, and our Node version is 12.16.1.

**Comment by danielweck** [comment]
`--raw` solved this problem for me.

**Comment by danielweck** [comment]
I tried various combinations of `COLORS=1` and `FORCE_COLOR=1` on the CLI, but `--raw` is what helped in the end.

**Comment by GerkinDev** [comment]
Seems related to the observable approach of concurrently's output, as mentioned the related issue in angular repo. Wouldn't it be possible to use a stream instead of an observable?

**Comment by paescuj** [comment]
Closing as it seems like this has been resolved on angulars side.
