### ISSUE TITLE
Is it possible to make a deployment of 2 services in heroku?

### ISSUE THREAD

**Issue by jasp402** [open-cli-tools/concurrently#242]
I have 2 services an **API** and a **graphQL**, the first is a static service so I start it with `node`, but the second is dynamic and I must use it with `nodemon`.

This is my `scripts` configuration

```
  "scripts": {
    "graphql": "nodemon ./4.ServiceLayer/graphql/app.js",
    "api": "node ./4.ServiceLayer/api/v1/app.js",
    "start": "concurrently \"npm run api\" \"npm run graphql\"",
  },
```

When I start it locally it works perfectly.
![image](https://user-images.githubusercontent.com/8978470/92306800-802f5400-ef57-11ea-8716-34f5e37b4c54.png)

But when I try to do the deployment in heroku I get an error. And basically it is understandable since it tries to connect both services to the same port.

![image](https://user-images.githubusercontent.com/8978470/92306824-b8cf2d80-ef57-11ea-9f4e-6f52241e739e.png)

Is there a solution to make a deployment of this type?

**Comment by paescuj** [comment]
Closing as it is related Heroku and not to `concurrently`.
