### ISSUE TITLE
SHELL_EXECUTE_FLAG should be explained in README

### ISSUE THREAD

**Issue by neillindberg** [open-cli-tools/concurrently#245]
Hi. I'm attempting to run a project that uses concurrently for the first time.
However, I run NodeJS projects everyday, all the time.
I'm on Windows, using GitBash, and in both stand alone and IDE embedded I've never seen this error in 10+ years of NodeJS development.
**'Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.'**

...from within:
./node_modules/spawn-default-shell/src/get-shell.js:  throw new Error(**'Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAG env variable.'**);

While this is not "concurrently" itself, it is a dependency of concurrently that raises this error.

I've never ever had to set this envar for any project, ever. I'm a full stack guy. I couldn't find any documentation on it, so I grep'd for it to get some hint of how to set it to what (above result omitted):
./node_modules/spawn-default-shell/README.md:* `SHELL_EXECUTE_FLAG=-c`
./node_modules/spawn-default-shell/src/get-shell.js:  if (process.env.SHELL_EXECUTE_FLAG) {
./node_modules/spawn-default-shell/src/get-shell.js:    return process.env.SHELL_EXECUTE_FLAG;
./node_modules/spawn-default-shell/test/test-platform-shared.js:    withEnv({ SHELL_EXECUTE_FLAG: '--execute' }, () => {
./node_modules/spawn-default-shell/test/test-platform-shared.js:    withEnv({ SHELL: '/bin/verycustomshell', SHELL_EXECUTE_FLAG: '-x' }, () => {

I would ask setting this be in your README for ease of use. I want to use this package to run a PERN stack app.

Both the npm scripts run fine on their own and this is only seen when using "concurrently".

I found that setting the flag to: `export SHELL_EXECUTE_FLAG=-c` works. But, totally not sure if it will mess with my 30 other projects that all have no problem runnning...?

**Comment by paescuj** [comment]
Closing this since the dependency "spawn-default-shell" has been replaced by "spawn-command" a long time ago (#89)...
