### ISSUE TITLE
Start Command only Running React App -Server not starting

### ISSUE THREAD

**Issue by agorfine** [open-cli-tools/concurrently#249]
Previously running npm start dev within the client folder ran both the react app and express server. Now it only runs the react app and does not start the server (React running on port 3000 instead of 3001)

**package.json client**
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@passbase/button": "^3.0.0-rc.11",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.0",
    "dotenv": "^8.2.0",
    "nodemon": "^2.0.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.0",
    "styled-components": "^5.2.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://localhost:3001/passbase"
}

**package.json root**
{
  "name": "fullapp",
  "version": "1.0.0",
  "description": "test full app",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js",
    "server": "nodemon server.js",
    "client": "cd client && npm start",
    "dev": "concurrently --kill-others-on-fail \"npm run server\" \"npm run client\""
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.21.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "morgan": "^1.10.0",
    "pg-promise": "^10.7.5"
  },
  "devDependencies": {
    "concurrently": "^5.3.0",
    "nodemon": "^2.0.6"
  }
}

**Comment by dalelotts** [comment]
`npm start dev` does not run the dev script.  Try `npm run dev`

You can close this issue, it is not a problem with this library.
