### ISSUE TITLE
Silent mode

### ISSUE THREAD

**Issue by ElegantScripting** [open-cli-tools/concurrently#25]
Can you make a silent mode?

When using concurrently for build systems, its prompt gets a bit annoying.

Thanks.

**Comment by kimmobrunfeldt** [comment]
How would you want the silent mode to work? Completely turn off output?

**Comment by gaggle** [comment]
I'd love a "silent stdout" arg that works like name, color, etc. So I can run multiple processes but silence those I don't care about.

**Comment by 0xcaff** [comment]
If you don't care about cross compatibility, you can do the following with modern bash:

    (npm run testrpc >& /dev/null) & npm run test

**Comment by PowerSupply** [comment]
It would be great to be able to specify the processes (by name/index) to silence stdout of

**Comment by Christilut** [comment]
Same here. Running `tsc --watch` and `ava --watch` at the same time, I don't care about the typescript compilation spam. Would be great if I can select only one command to be silent. Or even better, only show error output.

Maybe such options are nice to add to #102 ?

**Comment by gustavohenke** [comment]
If you are reading this, `--hide` flag is a thing since v6.4.0.
Run `concurrently --help` or see #173 to understand more.
