### ISSUE TITLE
Feature request: Run commands in sequence

### ISSUE THREAD

**Issue by MickL** [open-cli-tools/concurrently#257]
I know this module is about doing stuff in parallel. Anyway it is also very convenient to have something like `concurrently npm:build-*` and sometimes it is just needed to have something executed in sequence instead of parallel. Therefor I would love to have an option to do so, e.g. `concurrently npm:build-* --sync`

**Comment by lydell** [comment]
There’s a tool called [npm-run-all](https://github.com/mysticatea/npm-run-all) that you might be interested in.

**Comment by cdrini** [comment]
Haven't tried, but does `--max-processes 1` do this?

**Comment by Snaptags** [comment]
I can confirm `--max-processes 1` solves the probem, this issue should be closed.

@lydell npm-run-all seems kind of abandoned to me, probably people are coming here for a more "active" alternative?

**Comment by KBeDevel** [comment]
Maybe a `--sync` flag could be added as an alias of `--max-processes 1`.

P.D: Can confirm the flag solves the problem.
