### ISSUE TITLE
Not running npm scripts from an npm script

### ISSUE THREAD

**Issue by davidgilbertson** [open-cli-tools/concurrently#264]
I have the following scripts, nothing with `concurrently` in it works. I should be able to reference other npm scripts right? Or is that only when running from the command line?

```json
  "scripts": {
    "dev-api": "ts-node src/api/server.ts",
    "dev-web": "craco start",
    "cdev": "concurrently dev-*",
    "cdev1": "concurrently \"dev-*\"",
    "cdev2": "concurrently \"\"dev-*\"\"",
    "build": "craco build",
    "cbuild": "concurrently \"build\"",
  },
```
Versions:

npm: '6.14.8',
node: '14.14.0',
concurrently: `5.3.0`

Powershell 7 and Windows 10.

**Comment by martinkask-clarifai** [comment]
Add "yarn run" or "npm run" in front of the commands:
...// "cbuild": "concurrently \"yarn run build\"" //...

**Comment by gustavohenke** [comment]
Hey. You were close, the correct approach is `concurrently "npm:dev-*"`. What @martinkask-clarifai suggested also works!
