### ISSUE TITLE
Feature Request: Exponential backoff

### ISSUE THREAD

**Issue by mscottnelson** [open-cli-tools/concurrently#265]
Would be nice to have an exponential backoff feature when a process fails and you would like to restart it, but then allow that exponential backoff to be reset when the process is "alive" for a certain amount of time. As a start, this could even be simply allowing restartDelay option to take a function instead of a number.

Example:
- process fails -> immediate restart
- process fails -> restart after 2 seconds
- process fails -> restart after 4 seconds
- process fails -> restart after 8 seconds
- process "succeeds", where "success" is defined as "did not exit for 60 seconds after starting"
- process fails -> immediate restart
- process fails -> restart after 2 seconds

**Comment by gustavohenke** [comment]
Hey @mscottnelson! This sounds like a nice feature indeed.
Making `--restart-after` accept `exponential` as a special keyword would be nice.

**Comment by mscottnelson** [comment]
I see about putting together a pull request sometime this month.

**Comment by gustavohenke** [comment]
🚢 This is now available in v9.0.0!
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
