### ISSUE TITLE
Please fix tests to run on windows

### ISSUE THREAD

**Issue by Roaders** [open-cli-tools/concurrently#277]
Tests fail at the moment when running on windows. This makes it hard for others to contribute to the project.

**Comment by gustavohenke** [comment]
History on AppVeyor looks pretty stable to me:
https://ci.appveyor.com/project/kimmobrunfeldt/concurrently/history

Can you be more specific of where you are seeing this?

**Comment by Roaders** [comment]
any test that has sleep in it fails for me on windows. I had to remote to my raspberry pi to run the tests.
As far as I know sleep is not a thing on windows (but I might be wrong).

**Comment by loynoir** [comment]
@cben I think might be better to give to `sleep` pr to  [shelljs/shx](https://github.com/shelljs/shx/tree/master/src) ?

**Comment by loynoir** [comment]
Oh, sorry, lack of consideration. `shelljs` is implemented in a sync way, so seems `sleep` will not be adopted.

**Comment by thiagodp** [comment]
Same problem here. Using GitHub Actions with `ubuntu-latest`, `macos-latest`, `windows-latest` and it fails on `windows-latest` with Node `12` and `14`, but it works with Node `16`:

```bash
npx concurrently --success=first "npx foo" "(sleep 5 || timeout 5 > NUL) && npx bar"
```
Notes:
- `foo` and `bar` are hypothetical applications
- argument `--success` does not matter - same problem occurs using it or not

Real output:
![image](https://user-images.githubusercontent.com/2997844/149235215-6690fe56-adca-4d0d-b30a-57dac95fd181.png)

👉 It appears that `concurrently` is not parsing the arguments correctly for some reason.

**Comment by thiagodp** [comment]
@Roaders Try `sleep 5 || timeout 5 > NUL`

**Comment by paescuj** [comment]
Is this still a thing? Tests are working on GitHub CI with Windows (e.g. https://github.com/open-cli-tools/concurrently/runs/6467319393)

**Comment by gustavohenke** [comment]
@paescuj based on above feedback I was under the impression that it'd be because of the use of bash as the shell, but #337 is passing without it 🤔

**Comment by paescuj** [comment]
> @paescuj based on above feedback I was under the impression that it'd be because of the use of bash as the shell, but #337 is passing without it 🤔

Nice, that are good news 😃 Let me test it out on my Windows setup next weekend just to be 100% sure... Afterwards we can close this issue!

**Comment by paescuj** [comment]
> > @paescuj based on above feedback I was under the impression that it'd be because of the use of bash as the shell, but #337 is passing without it 🤔
> 
> Nice, that are good news 😃 Let me test it out on my Windows setup next weekend just to be 100% sure... Afterwards we can close this issue!

Indeed, there are some issues with the tests on Windows... I'm going to investigate it as soon as I have time!
