### ISSUE TITLE
Concurrently doesn't exit after last command is run with pnpm

### ISSUE THREAD

**Issue by mellson** [open-cli-tools/concurrently#290]
When I run a script with `pnpm` it doesn't exit to the terminal after my scripts are finished. But if I run the script using `npm` it exits just fine when it's done. Running the scripts on their own exits just fine using `pnpm`.

The script looks like this: `concurrently -m 1 -r pnpm:add-type-to-package-json pnpm:test-watch pnpm:remove-type-from-package-json`

Any ideas on how to make it exit to the terminal when it's done?

**Comment by gustavohenke** [comment]
Hey @mellson, there's nothing inherently broken with those flags + pnpm combination.
Are you able to come up with a small self contained repo + environment information so that I can test it on my own?

**Comment by mellson** [comment]
Hey, @gustavohenke, that sounds good. I'm not using the project anymore, so I can't even recreate it locally. Therefore I am closing this for now; thanks for the reply!
