### ISSUE TITLE
No more working with yarn 3

### ISSUE THREAD

**Issue by MickL** [open-cli-tools/concurrently#292]
I just upgraded to yarn 3.1.0 and now concurrently doesnt seem to work anymore.

package.json
```json
"start": "concurrently yarn:start:*",
"start:app": "ng serve",
"start:storybook": "start-storybook -p 4201",
```

Shell:
```shell
yarn start
No matches found: "yarn:start:*"
```

**Comment by ianpogi5** [comment]
I'm experiencing the same issue.

**Comment by gustavohenke** [comment]
@MickL can you try wrapping `yarn:start:*` in quotes, e.g. `"start": "concurrently 'yarn:start:*'"`?
the error you describe, `No matches found: "yarn:start:*"` isn't even from concurrently 😕 

@ianpogi5 can you try the above too?

**Comment by gustavohenke** [comment]
Seems same thing with npm-run-all. https://github.com/mysticatea/npm-run-all/issues/196#issuecomment-801480051

**Comment by gustavohenke** [comment]
I've added docs to teach how to do this, but yeah apparently it's won't fix resolution. Yarn/shell kicks in before concurrently has a chance to.

**Comment by ianpogi5** [comment]
> @MickL can you try wrapping `yarn:start:*` in quotes, e.g. `"start": "concurrently 'yarn:start:*'"`? the error you describe, `No matches found: "yarn:start:*"` isn't even from concurrently confused
> 
> @ianpogi5 can you try the above too?

Yeah wrapping in quotes seems to work. Thanks @gustavohenke !

**Comment by MickL** [comment]
I think the issue occurs in yarn 2 and 3

**Comment by gustavohenke** [comment]
Yup it does @MickL! Same solution still applies.
