### ISSUE TITLE
Process still running after exiting (SIGINT) from all spawned processes

### ISSUE THREAD

**Issue by denik1981** [open-cli-tools/concurrently#298]
I'm trying to set a very simple configuration to concurrently run a localtunnel that points to a next localhost server.

The npm script is `"concurrently -k \"next dev\" \"node tunnel/index.js\""` 
This scripts work well independently and they do so with concurently.
The problem I'm facing is when I tried to exit from any of those, I got the visual feedback on stdout that clearly tells me that SIGINT was sent to both processes but the "master" process (concurrently) is still running and don't return my prompt back. I have to sent an extra SIGINT to end it.

I have tried the same command without the "k" flag, tried using the --kill-others-on-fail flag  and even the "s" flag with its 3 different settings. None of this configurations seems to solve the problem. 
 
 ```
 $ yarn run dev
yarn run v1.22.17
$ concurrently "next dev" "node tunnel/index.js"
[0] ready - started server on 0.0.0.0:3000, url: http://localhost:3000
[0] info  - Loaded env from /home/demian/Documents/CODE/SHOPIFY/apps/shopify-next-app/.env.local
[1] https://4490f7e2-6938-4ae2-9e4f-9106edc4ec4c.loca.lt
[0] event - compiled successfully in 2.3s (188 modules)
^C
demian:~/Documents/CODE/SHOPIFY/apps/shopify-next-app [master] 
$ [1] node tunnel/index.js exited with code SIGINT
[0] next dev exited with code SIGINT

```
The last blank line is the cursor hanging on the process which won't return my prompt back if I don't sent an extra SIGINT.
To be clear both processes running independently don't need an extra SIGINT to exit. This happens only when they are spawn by concurrently. And I'm not spawing any extra process within the localtunnel. The code for the tunnel is fairly simple.

```
const localtunnel = require("localtunnel");
const { exec } = require("child_process");
const { randomUUID } = require("crypto");
const fs = require("fs");
const { join } = require("path");

let uuid = "";
const uuidPath = join(__dirname, "uuid");

// Making your tunnel URL unique and persistant across executions
if (fs.existsSync(uuidPath)) {
  uuid = fs.readFileSync(uuidPath, "utf8");
} else {
  uuid = randomUUID();
  fs.writeFileSync(uuidPath, uuid);
}

// https://github.com/localtunnel/localtunnel#api
const init = async () => {
  const tunnel = await localtunnel({ port: 3000, subdomain: uuid });
  console.log(tunnel.url);
  tunnel.on("close", () => {});
};

init();
```

**Comment by tjni** [comment]
I ran into this also, but I don't think the parent process is still alive. Instead, the parent process dies before the children die.

We can see this in your command line output:
```
^C
demian:~/Documents/CODE/SHOPIFY/apps/shopify-next-app [master] 
$ [1] node tunnel/index.js exited with code SIGINT
```
The prompt is provided, but the child process logs something additionally when it dies. Simply pressing something like `<Enter>` should print a new prompt.

I could not find a way in Node to delay shutting down the parent process until the child processes shut down.

The issue https://github.com/pkrumins/node-tree-kill/issues/35 requests a way to synchronously shut down child processes, but this could be hard as well.

**Comment by gustavohenke** [comment]
Hey all. Is there more information to reproduce this issue? OS, self contained repo maybe?

**Comment by tjni** [comment]
I appreciate the question, as trying to find a reproducer led me to understand that this is not likely to be a problem in concurrently (at least, not directly). I now think that this is due to an issue in both PNPM and Yarn: https://github.com/pnpm/pnpm/issues/2653

**Comment by denik1981** [comment]
@tjni Actually that last `^C` that is logged into the console is the signal from the extra CTRL+C I was needing to end the process. Only after that is when the prompt returns back to me. For the second run, I kill the 2 concurrent process so to show here that the prompt isn't coming back to me when there is nothing more there to kill.

**Comment by compulim** [comment]
On my side, the problem is from `lerna@4`, which I use to run `concurrently`.

https://github.com/lerna/lerna/issues/2284

I tested few scenarios on Windows (outside of `lerna`), like nesting `concurrently` and it looks good to me so far.

**Comment by denik1981** [comment]
I will close this issue due to the lack of activity
