### ISSUE TITLE
Is there a changelog?

### ISSUE THREAD

**Issue by Flimm** [open-cli-tools/concurrently#300]
I'm looking for a release log for `concurrently`, to understand if I can safely upgrade from `concurrently` 5.0 to 6.0. I can't find it. Is there a changelog?

**Comment by gustavohenke** [comment]
https://github.com/open-cli-tools/concurrently/releases

**Comment by gustavohenke** [comment]
Ok, expanding more on the above:
Only breaking change since 5.x.x is the drop of Node 8 support. There have been a couple of important bug fixes/security updates and nice features added (`--hide` and `--timings` flags) since then.

**Comment by Flimm** [comment]
Thank you! I didn't think of looking at the GitHub release pages for this repo.
