### ISSUE TITLE
--group option shows only first output

### ISSUE THREAD

**Issue by DavideViolante** [open-cli-tools/concurrently#301]
1. Clone [this repo](https://github.com/DavideViolante/Angular-Full-Stack)
2. Run `npm i`
2. Run `npm run dev`
3. See several output from 4 different commands
4. Edit `package.json` and add --group option to `dev` script
5. Run `npm run dev`
6. See output (only output from first command is showed)

**Comment by gustavohenke** [comment]
What you're saying seems about right, maybe `--group` needs more documentation.
It isn't tailored for long running processes (like servers, in your case) as it'll only print a command's output after all previous ones exit.

```
$ concurrently "echo foo" "echo bar; sleep 2; echo bar"
[0] foo
[1] bar
[0] echo foo exited with code 0
[1] bar
[1] echo bar; sleep 2; echo bar exited with code 0

$ concurrently --group "echo foo" "echo bar; sleep 2; echo bar"
[0] foo
[0] echo foo exited with code 0
[1] bar
[1] bar
[1] echo bar; sleep 2; echo bar exited with code 0
```
