### ISSUE TITLE
How do you exclude with patterns?

### ISSUE THREAD

**Issue by NullVoxPopuli** [open-cli-tools/concurrently#305]
for example, `npm-run-all` has the ability to do this:
```
    "lint": "npm-run-all --aggregate-output --continue-on-error --parallel 'lint:!(fix)'",
```
where it runs: `lint:js`, and `lint:md` but not `lint:js:fix` or `lint:md:fix`

can concurrently omit via pattern?

**Comment by gustavohenke** [comment]
Nope, this isn't possible at the moment.
Best you can do is add some suffix to your scripts, e.g. `lint:js:main`, and then run `concurrently "npm:lint:*:main"`

**Comment by NullVoxPopuli** [comment]
would a PR to support this be of interest?

**Comment by gustavohenke** [comment]
I don't know if many people ever needed something like this, so I'm keen to see how complex it can get -- if it turns out being a simple solution to implement and document, sure!
