### ISSUE TITLE
No Matches Found with yarn berry + wildcards

### ISSUE THREAD

**Issue by osdiab** [open-cli-tools/concurrently#309]
Seems that `concurrently` doesn't properly find ~packages~ `package.json` scripts when specified with wildcards on Yarn 3.2.0. Is it not supported? Thanks!

**Comment by gustavohenke** [comment]
Which packages do you mean?

**Comment by osdiab** [comment]
sorry I mean scripts. Like if I add a script like so to my `package.json`:

```
concurrently 'npm:dev-*`
```

or 

```
concurrently 'yarn:dev-*`
```

or

```
concurrently 'dev-*`
```

and have other scripts like `dev-app` `dev-api`, then it fails saying that it can't find any packages matching the name.

**Comment by gustavohenke** [comment]
Are you getting `No matches found:  ...`? If yes, this is the same problem as #292.
One thing is to try using matching quotes 😄 

E.g.
```diff
-concurrently 'npm:dev-*`
+concurrently 'npm:dev-*'
```

**Comment by osdiab** [comment]
oh yeah, same thing! thanks!
