### ISSUE TITLE
Problem: you have not yet been thanked

### ISSUE THREAD

**Issue by boutell** [open-cli-tools/concurrently#310]
Thanks to the developers of this tremendously useful utility. Even in bash scripts I find `npx concurrently` to be absolutely essential.

**Comment by gustavohenke** [comment]
Ah it's awesome to know that concurrently has been helping someone!! ❤️ 

I hope you can keep finding it useful as it gets improved.
Any bugs or feature requests are welcome to be filled as separate issues!
