### ISSUE TITLE
Possibility to hide output from API

### ISSUE THREAD

**Issue by L-TheG** [open-cli-tools/concurrently#313]
Hi,

it would be really cool if it was possible to hide the output of a command, when it is launched from the API.
I couldn't find anything like this in the documentation so I thought I might just suggest it.

It could look something like this:
```
const concurrently = require('concurrently');

const command = concurrently(
   [
      {
         command: 'command nr 1 ',
         name: 'cmd1',
      },
      {
         command:'command nr 2',
         name: 'cmd2 with hidden output',
         hide: true
      },
   ],
);
```

Cheers!

**Comment by gustavohenke** [comment]
Not very ergonomic and somehow also not documented (unless you use Typescript), but you can do so in the options object:

https://github.com/open-cli-tools/concurrently/blob/16465159b0f8b24ad178d5f014e032ba53d6284d/src/index.ts#L15-L20

Example:

```js
concurrently([...commands], {
  // Will hide command(s) with this name
  hide: ['cmd2 with hidden output'],
  // Will hide command(s) with these indices
  hide: [1, 5]
})
```
