### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by paescuj** [open-cli-tools/concurrently#323]
* "main" is a less offensive term than "master" (see https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main).
* "main" is now the default branch for new repositories on GitHub.
* A lot of repositories have already switched from "master" to "main".

Renaming just takes a few seconds, see https://github.com/github/renaming#renaming-existing-branches.

**Comment by gustavohenke** [comment]
Done ✅

**Comment by paescuj** [comment]
Nice, thx! 🥇

**Comment by gustavohenke** [comment]
had totally forgotten that CI would stop running, so 74412badf0eb5402dc83fdca74843eeb305304fd

**Comment by paescuj** [comment]
> had totally forgotten that CI would stop running, so [74412ba](https://github.com/open-cli-tools/concurrently/commit/74412badf0eb5402dc83fdca74843eeb305304fd)

Sorry, me too! I've planned to submit a PR but forgot about it 🙈
