### ISSUE TITLE
Sequence or Delays

### ISSUE THREAD

**Issue by isaadabbasi** [open-cli-tools/concurrently#327]
I am using concurrently in a monorepo, where some packages are dependent on each other. 
The following script elaborates the sequences processes needs to run. 

```
const { result } = concurrently([
  {
    command: 'npm run build:watch',
    name: 'shared',
    cwd: path.resolve(process.cwd(), 'packages/shared'),
  },
  {
    command: 'npm run build:watch',
    name: 'db',
    cwd: path.resolve(process.cwd(), 'packages/db'),
  },
  {
    command: 'npm run dev',
    name: 'gql',
    cwd: path.resolve(process.cwd(), 'packages/gql'),
  },
], {
  killOthers: ['failure'],
  prefix: 'someproject',
  restartTries: 3,
  resartDelay: 3000
})
```
I wan't these scripts to run sequentially. I get that - the entire point of this package is concurrently running processes (not sequentially). 
Can i some how run these with delays in between 
2 seconds wait after `packages/shared` build
2 seconds wait after `packages/db` build
build `packages/gql`

**Comment by gustavohenke** [comment]
This request is similar to #265.
You can also already do it with the programmatic API like this: https://github.com/open-cli-tools/concurrently/issues/201#issuecomment-542898983

But honestly, you will have some sort of flakiness when depending exclusively on time to have your builds passing.
https://github.com/open-cli-tools/concurrently/issues/201#issuecomment-693320616 lists a way using `wait-on` which is a great tool for waiting for e.g. a file or server to be available.
