### ISSUE TITLE
Spawn a process for each file in a directory

### ISSUE THREAD

**Issue by archubbuck** [open-cli-tools/concurrently#341]
I'm running into some scalability issues using the following approach:

```
{
    "scripts": {
      "mass": "concurrently \"npm:accounts/*\"",
      "accounts/1": "ts-node src/index.ts --settings %npm_lifecycle_event%.json",
      "accounts/2": "ts-node src/index.ts --settings %npm_lifecycle_event%.json",
      "accounts/3": "ts-node src/index.ts --settings %npm_lifecycle_event%.json"     
    }
}
```

_Note: `%npm_lifecycle_event%` evaluates to the name of the npm script (e.g. accounts/1)_

Ideally, I would like to be able to just specify the directory, then have concurrently spawn a new process for each file in that directory, passing the path to the file to the underlying script. 

Is there a way to do this? Currently, I need to add a new script for each account file manually.

**Comment by paescuj** [comment]
Was about to suggest exactly this! 👍 Thanks for reporting back!
