### ISSUE TITLE
Hide "exited with code" output

### ISSUE THREAD

**Issue by davidosomething** [open-cli-tools/concurrently#373]
Add flag to hide the "exited with code" output

**Comment by gustavohenke** [comment]
Would you still want to know other situations which made the process exit?

**Comment by paescuj** [comment]
You might be interested in the `--raw` option, see https://github.com/open-cli-tools/concurrently#usage.

I'm going to close this for now. If you're still interested in such a feature, please open a new issue and provide more information, in particular:
- Use Case: Why is this needed and what is a use case for it?
- Expected solution: Should all meta outputs from "concurrently" be suppressed (as @gustavohenke asked)? How is it different from the `--raw` option?

Thank you!
