### ISSUE TITLE
--hide param doesn't work with --raw output

### ISSUE THREAD

**Issue by top-kat** [open-cli-tools/concurrently#394]
I have tried: 
``` bash
concurrently --kill-others "npm run build:watch" "npm run start:pm2" -r --hide "0"
# OR 
concurrently --kill-others "npm run build:watch" "npm run start:pm2" -r --hide 0
```

But hiding works only when I remove the `-r` (raw) param.

Sorry if this is intended behavior.

**Comment by paescuj** [comment]
I can confirm that the `hide` option is ignored in `raw` mode, but I don't know whether this is intended or not.
Do you happen to know this @gustavohenke?
I'll gladly adjust this in a pull request, if it's not an intended behavior.

**Comment by gustavohenke** [comment]
Why the bug happens I think sorta makes sense -- stdio is inherited from the parent:
https://github.com/open-cli-tools/concurrently/blob/ed3c18f7849c73df552f6b67fe4e68d030aa1bb1/src/get-spawn-opts.ts#L42

And it should probably be fixed, yes.

**Comment by fabiiomiiguel** [comment]
Hello @gustavohenke 😁 First of all, thank you for this amazing tool.

I'm here just to ask, if you plan to publish this fix anytime soon?

**Comment by PoQuatre** [comment]
Hello @gustavohenke  I did a PR fixing this issue (#486) around 2 weeks ago, but it still has no responses, so I was wondering if PRs are still welcome for this?

**Comment by gustavohenke** [comment]
It's merged :slig

**Comment by gustavohenke** [comment]
Hi folks, sorry for the delay, this is now done in v9.0.0.
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
