### ISSUE TITLE
Newline is not passed from input to specific child

### ISSUE THREAD

**Issue by everhardt** [open-cli-tools/concurrently#397]
When I run concurrently with `--handle-input` for multiple [`ts-node-dev`](https://github.com/wclr/ts-node-dev) processes (with `--rs`), I can only trigger a restart of the default child, by entering `rs` and pressing enter. When I try `1:rs`, it never triggers a restart. When I try `0:rs` it only triggers a restart when I press enter twice. 

This behaviour is caused by [the regex](https://github.com/open-cli-tools/concurrently/blob/ed3c18f7849c73df552f6b67fe4e68d030aa1bb1/src/flow-control/input-handler.ts#L54) identifying the child: it filters out the newline of the command.

**Comment by gustavohenke** [comment]
Hey, there has been some improvements to input handling since you've opened this issue: #393

Can you try v8.2.0 or newer, and let us know if it works better?

**Comment by everhardt** [comment]
Yes, that works!
