### ISSUE TITLE
Import footgun: Default export versus named export (No output when used via API)

### ISSUE THREAD

**Issue by rezonant** [open-cli-tools/concurrently#399]
I got bit by accidentally importing as `import { concurrently } from 'concurrently';` instead of `import concurrently from 'concurrently';`. The default export applies all the default controllers and logger, whereas the named export does not (the default export uses the "unconfigured" named export to do it's thing). 

It might be worth adding a note to the README about this or possibly renaming the named export to make it harder to fall into this trap. 

The symptoms are that no program output appears, even though it does when you use the concurrently CLI- this is of course because there is no Logger or LogOutput/LogError controllers added in the configuration.
I ended up having to dig into the source code to figure this out.

At the very least, this issue should provide some help for anyone else who hits this footgun.

**Comment by gustavohenke** [comment]
You've raised an excellent point!
I suppose that renaming the unconfigured function to `createConcurrently` would be better, but that'd be a breaking change 😕

**Comment by paescuj** [comment]
> I suppose that renaming the unconfigured function to `createConcurrently` would be better, but that'd be a breaking change 😕

Might be something for v8?

**Comment by gustavohenke** [comment]
Hey! This is now fixed in v9.0.0.
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
