### ISSUE TITLE
Bug:  The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by TerrySlack** [open-cli-tools/concurrently#401]
For bug reports, please provide the following information:

Following the directions in the docs:
yarn add concurrently -D

In the scripts sections of package.json I added the following script
```
"dev-start": "concurrently \"clean:css\" \"build:css:dev \" \"dev:local\"",
```
I get the following output
```
> concurrently "clean:css" "build:css:dev " "dev:local"

[0] The filename, directory name, or volume label syntax is incorrect.
[1] The filename, directory name, or volume label syntax is incorrect.
[2] The filename, directory name, or volume label syntax is incorrect.
[0] clean:css exited with code 1
[1] build:css:dev  exited with code 1
[2] dev:local exited with code 1
```

Expected Behavior:
All 3 scripts would be run concurrently
If I run them sequentially, using  "dev-start": "yarn clean:css && yarn build:css:dev  && yarn dev:local
No issues.
I wanted to use concurrently, in order to add a --watch flag to build:css:dev

Environment:
Windows 11
yarn 1.22.19
VS Code

Reproduction
Download and follow the instructions given in the docs

**Comment by paescuj** [comment]
You need to prefix the commands with the `yarn` shortcut (see https://github.com/open-cli-tools/concurrently#usage):
```
"dev-start": "concurrently \"yarn:clean:css\" \"yarn:build:css:dev \" \"yarn:dev:local\""
```
Otherwise the arguments are executed as normal commands.
