### ISSUE TITLE
Inconsistent exit codes across OSes

### ISSUE THREAD

**Issue by 40x** [open-cli-tools/concurrently#405]
I am using the package to run my integration tests. It does two things

1. start the webpack dev server 
2. run the jest tests against it 

Tests run successfully and exit with 0, that in turn triggers the SIGTERM being sent to other processes (as shown in the logs) but the exit code sent to the process on windows is 1 while it is SIGTERM on mac. 

We rely on SIGTERM to do some clean-up but because of the way it exits right now, we are unable to do so only on windows.

On Windows - 
<img width="859" alt="image" src="https://user-images.githubusercontent.com/10065828/220861110-21298dc0-9700-4955-9092-2c12505e57af.png">

On Mac - 
![image](https://user-images.githubusercontent.com/10065828/220861487-82483e73-7d07-41d6-b2ed-9f020754c085.png)

**Comment by gustavohenke** [comment]
Well, yeah. Windows doesn't have signals AFAIK
