### ISSUE TITLE
Unexpected token '?'

### ISSUE THREAD

**Issue by sukheja-varun** [open-cli-tools/concurrently#413]
Getting unexpected token in the latest 8.0.1 and 8.0.0 versions when trying to run any concurrently commands
It is working fine till v7.6.0

<img width="384" alt="image" src="https://user-images.githubusercontent.com/21065146/229370724-d686861d-3ca1-4c61-ba46-8ca5d214983f.png">

**Comment by gustavohenke** [comment]
What's your node version?
8.0.0 dropped support for Node 12, which allows concurrently to make use of syntax such as `?.`.

**Comment by gustavohenke** [comment]
Right! In this case please upgrade to Node 14, or stick to concurrently v7.
