### ISSUE TITLE
Can I run some scripts concurrently but some others in a series?

### ISSUE THREAD

**Issue by sandrooco** [open-cli-tools/concurrently#419]
I have the following steps in my CI:

1. `lint:errors-only`
2. `prettier:check`
3. `test`
4. `build:ngssc`
5. `gzip`

Is it actually possible to run 1-3 concurrently and then 4-5 serially? This is needed because `gzip` depends on the output from the command above.

**Comment by gustavohenke** [comment]
```
concurrently lint:errors-only prettier:check test "build:ngssc && gzip"
```

?
