### ISSUE TITLE
Command `node` not run in Windows (PowerShell and Cmd)

### ISSUE THREAD

**Issue by alexandrogs** [open-cli-tools/concurrently#429]
```
> concurrently 'node prisma/seeds/userSeed.js'
[0] ...
[0] ...
[0] 'node exited with code 1
```
Node v20.3.1 AND Node v18.16.1
Node v16.16.0 is in error

**Comment by paescuj** [comment]
Try with `concurrently "node prisma/seeds/userSeed.js"` as single quotes are not supported on Windows.
See also the examples under https://github.com/open-cli-tools/concurrently#usage.

**Comment by ilixindri** [comment]
I tested and not run!

**Comment by paescuj** [comment]
What's the error message?

**Comment by gustavohenke** [comment]
Are you using regular command prompt? I briefly remember that Windows doesn't support single quotes to wrap command line arguments:
https://superuser.com/q/324278/200254

I wouldn't be surprised if this still is the case nowadays.
