### ISSUE TITLE
No colors for prefixes when using `prefixColors: "auto"` via concurrent API

### ISSUE THREAD

**Issue by OnkelTem** [open-cli-tools/concurrently#437]
concurrently: 8.2.1
node: v16.17.0

I use the following script to run concurrent processes:

```js
const fs = require('fs')
const path = require('path')
const concurrently = require('concurrently')

const workspacePaths = JSON.parse(fs.readFileSync('./package.json')).workspaces

const { result } = concurrently(
  workspacePaths.map((wp) => ({
    command: 'npm:dev',
    name: path.basename(wp),
    cwd: path.resolve(__dirname, '../', wp),
  })),
  {
    prefix: 'name',
    killOthers: ['failure', 'success'],
    restartTries: 0,
    prefixColors: 'auto',
  }
)

result.then(
  () => {
    console.log('Success')
  },
  () => {
    console.log('Failed')
  }
)
```

However, when I run in the terminal, it doesn't show any colors in the prefixes:

![image](https://github.com/open-cli-tools/concurrently/assets/114060/debfed7f-74ae-4307-8590-c19166c27601)

yet other colors are displayed. What could be the problem?

Thanks in advance.

**Comment by SeiwonPark** [comment]
Check out API's `prefixColors`. It says

### Docs
<p><code>prefixColors: <b>a list of colors</b> as supported by chalk or auto for an automatically picked color. </code></p>

### Definition
```
prefixColors?: string[]
```

<br />   

So change it to 

```js
prefixColors: ['auto'],
```

**Comment by paescuj** [comment]
I think @SeiwonPark is right! (Thanks!)
Therefore I'm closing this issue for now, but let me know if that doesn't work either and we'll reopen it.

**Comment by OnkelTem** [comment]
Thanks @SeiwonPark

However, an update to the docs was made:

> `prefixColors`: a list of colors or a string as supported by [chalk](https://www.npmjs.com/package/chalk) and additional style `auto` for an automatically picked color.

And I support it. Now it sounds much better.
