### ISSUE TITLE
Allow commands IPC

### ISSUE THREAD

**Issue by odeadglaz** [open-cli-tools/concurrently#465]
Hey 👋 

Currently when spawning commands via `concurrently`, you cannot send messages from spawned process to top process due to the fact that the ['spwanOptions'](https://github.com/open-cli-tools/concurrently/blob/main/src/get-spawn-opts.ts#L4) won't allow it.

It might be useful to allow consumers to configure this in order to allow `ipc` and create communication in between.

If this something that make sense for you, would love to contribute it 👍 

Example of what potentially I would want:
```
// test.ts
  const concurrency = concurrently([
      { name: 'Child Process', command: 'ts-node ./test2.ts'  },
  ], {
      killOthers: ['failure'],
  });
  const [subProcess] = concurrency.commands;

  subProcess.process?.on('message', (data) => {
      console.log('Sub process message:', data);
  });

 subProcess.process?.send({ parent: true });
```

```
//test2.ts
process.send?.({ child: true });

process.on('message', (msg) => {
    console.log('Message from parent:', msg);
});
```

**Comment by gustavohenke** [comment]
Great suggestion, let's add it! 😄

**Comment by odeadglaz** [comment]
Glad to hear, I can attach it to my open PR and resolve the two issues at once 🌮

**Comment by odeadglaz** [comment]
I tried adding it to the above mentioned PR, altho failed due to [this issue](https://github.com/moxystudio/node-cross-spawn/issues/137). Do you plan to drop support for `Node@16` over next major ? If so It won't be an issue rather just delaying this one.

**Comment by gustavohenke** [comment]
Maybe, it's not in LTS anymore. But each feature in its own PR, please
