### ISSUE TITLE
API (concurrently) not printing to stdout unless raw=true

### ISSUE THREAD

**Issue by rr326** [open-cli-tools/concurrently#478]
Using the `concurrently()` API, it is not printing to stdout, unless `raw:true`.

## test.js
```js
import { concurrently } from "concurrently"

const build = {
    command: "ls -al",
    name: "TSC",
},
servDev = {
    command: "ls -al ",  
    name: "SERVER",
},
cmds =  [build, servDev]


const {result} = concurrently(cmds, {raw:false})
```

`node test.js` 
No output.

Set `raw:true` ==> expected output
```
# macos

node --version
v21.7.2

npx concurrently -v
8.2.2
```

**Comment by gustavohenke** [comment]
I think you might've hit the same issue as #399.

```diff
- import { concurrently } from "concurrently"
+ import concurrently from "concurrently"
```

should fix it.

**Comment by rr326** [comment]
@gustavohenke Thank you! That makes sense.

**Comment by CodeSmith32** [comment]
Just fyi, this is *really* confusing, esp. since VSCode / TypeScript likes to import the named version automatically by default.

I'm so glad I stumbled across this *closed* issue; otherwise I would've given up.

Is this really not something that could be fixed or at least clarified? Is there ever even a reason to import the named version / does any project actually rely on it?

**Comment by rr326** [comment]
@gustavohenke Is there a way to throw a warning (console.log) if it is imported and used improperly? Or even just if it is imported and used this way? That might strike the right balance between not breaking anything, and preventing people from making this very hard to spot mistake. 

As someone who uses tons of open source projects of which I just skim the docs, I really value when they print a warning saying, "Hmmm... are you really intending to use this in this really dumb way?"

**Comment by gustavohenke** [comment]
Hey folks, your concerns should be fixed on the main branch by #456, it's just that there are a few other major/breaking changes coming along too.

**Comment by rr326** [comment]
@gustavohenke That's awesome. Thank you Gustavo.

**Comment by gustavohenke** [comment]
Hey! This is now done in v9.0.0.
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
