### ISSUE TITLE
on sending --kill-others process ng serve close with exit code 1

### ISSUE THREAD

**Issue by ramialkheshan** [open-cli-tools/concurrently#481]
Hello! I have the next problem and this is my steps for reproduce:
1) I have main **package.json** where 

```typescript
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "stop": "taskkill -f -im node* && exit 0",
    "start4tests": "node ./src/scripts/runNgServeForTests.ts",
    "build": "ng build",
    "**test:integration**": "concurrently --kill-others --kill-signal SIGKILL --success all \"npm run start4tests\" \"wait-on http://localhost:4200/ && cd ./tests/wdio && npm install && npm run test:integration\"",
``` 
    
2) On my another **package.json** on test project  I have this:
```typescript
"test:integration": "cross-env TT_ENV=LOCAL wdio run ./config/wdio.integration.conf.ts",
``` 
3) In file ./src/scripts/runNgServeForTests.ts I have next code:
```typescript
const { spawn } = require('child_process');

const ngServe = spawn('ng', ['serve', '--configuration=test'], { shell: true });

process.on('SIGINT', () => {
  console.log('SIGINT signal received. Shutting down gracefully...');
  ngServe.kill('SIGINT');
  process.exit(0);
});

ngServe.on('close', () => {
  process.exit(0);
});

``` 
And After running command 
/npm run test:integration

I got next result in my terminal 

![image](https://github.com/open-cli-tools/concurrently/assets/171002191/aec844b2-3338-442c-8879-098fd7d14495)

By the way I have tested without --kill-signal SIGKILL and result was the same

Could you help me understand how I can close ng serve process with exited code 0 ?

**Comment by gustavohenke** [comment]
Try setting the `--success` flag, it allows you to set which process(es) you want to infer the exit code 0 from.

**Comment by ramialkheshan** [comment]
> `--success`

Sorry, this flag present in my command with value **all**. So maybe you will advice to me something else. I will be very grateful
![image](https://github.com/open-cli-tools/concurrently/assets/171002191/df47c195-02d1-48d6-9fe3-5eed3dfcc540)
