### ISSUE TITLE
Try setting the `--success` flag, it allows you to set which process(es) you want to infer the exit code 0 from.

### ISSUE THREAD

**Issue by ramialkheshan** [open-cli-tools/concurrently#485]
Try setting the `--success` flag, it allows you to set which process(es) you want to infer the exit code 0 from.

_Originally posted by @gustavohenke in https://github.com/open-cli-tools/concurrently/issues/481#issuecomment-2136283009_

> `--success`

Sorry, this flag present in my command with value **all**. So maybe you will advice to me something else. I will be very grateful
![image](https://github.com/open-cli-tools/concurrently/assets/171002191/df47c195-02d1-48d6-9fe3-5eed3dfcc540)

**Comment by gustavohenke** [comment]
Please don't open new issues unless they are for problems unrelated to this.
