### ISSUE TITLE
Is there a way to withhold output and then print serially when all commands exit?

### ISSUE THREAD

**Issue by bruce-c-liu** [open-cli-tools/concurrently#506]
Hi, is there a way to withhold all output and then print all output serially when all commands exit?

For example, I use execute eslint and tsc with `concurrently`. However, their output is interspersed, which makes reading the actual errors confusing. It would be great if `concurrently` could "withhold" all the output until both eslint and tsc finish. Then, it could log everything from eslint first, and then everything from tsc.

**Comment by gustavohenke** [comment]
Not when _all_ exit, but you can do it as each command (as per input order) exits.
https://github.com/open-cli-tools/concurrently/blob/v9.0.1/docs/cli/output-control.md#grouping

**Comment by bruce-c-liu** [comment]
Oh sweet!

```shell
concurrently -g "eslint" "tsc"
```
Just to confirm, the above command would run eslint and tsc concurrently. It will buffer `tsc`'s output while it waits for `eslint` to exit. And when `eslint` exits, it outputs all of `tsc`'s output all at once. Is that correct?

**Comment by gustavohenke** [comment]
Correct 👍

**Comment by bruce-c-liu** [comment]
Perfect, exactly what I needed. Thank you!
