### ISSUE TITLE
How to run WSL command in windows

### ISSUE THREAD

**Issue by aramis-it** [open-cli-tools/concurrently#507]
It works in cmd>  wsl bash -c 'echo password | sudo -S service redis-server start' 

With concurrently not wokring. How to run it?
>concurrently "wsl bash -c 'echo password | sudo -S service redis-server start'"
[0] 'sudo' is not recognized as an internal or external command,
[0] operable program or batch file.
[0] wsl bash -c 'echo password | sudo -S service redis-server start' exited with code 255

**Comment by gustavohenke** [comment]
Hey! I'd love to look at this, but I'm on Mac ARM which apparently doens't support nested virtualisation through UTM yet (https://github.com/utmapp/UTM/issues/4056#issuecomment-1433850890).
Have tagged this issue as 'help wanted'. Pull requests welcome, if anyone finds a way to fix it.
