### ISSUE TITLE
MaxListenersExceededWarning in 9.0.1

### ISSUE THREAD

**Issue by arianmares** [open-cli-tools/concurrently#510]
Hi,
I am using node v18.16.0 with concurrently v9.0.1
After calling concurrently few times with 20-30 commands I am getting this warning:

(node:3690238) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at process.addListener (node:events:605:10)
    at /var/node/node_modules/concurrently/dist/src/flow-control/kill-on-signal.js:19:26
    at Array.forEach (<anonymous>)
    at KillOnSignal.handle (/var/node/node_modules/concurrently/dist/src/flow-control/kill-on-signal.js:18:41)
    at options.controllers.reduce.commands.commands (/var/node/node_modules/concurrently/dist/src/concurrently.js:65:51)
    at Array.reduce (<anonymous>)
    at concurrently (/var/node/node_modules/concurrently/dist/src/concurrently.js:64:46)
    at concurrently (/var/node/node_modules/concurrently/dist/src/index.js:48:44)

The code sequence I am using is this:

```
function test(commands){
var mockedStream = new PassThrough();
const { result } = concurrently(
			commands,
			{
				outputStream:mockedStream,
				prefixColors:false
			},
		);
		result.then((res)=>{
			console.log(res);
		}, (res)=>{
			console.log(res);
		});
}_
```
The commands array is looking as follows:
```
_[
  'sshpass -p admin ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ConnectTimeout=7 admin@10.72.107.88 << EOF\n' +
    'version\n' +
    'EOF',
  'sshpass -p admin ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ConnectTimeout=7 admin@10.131.253.212 << EOF\n' +
    'version\n' +
    'EOF',
  'sshpass -p admin ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ConnectTimeout=7 admin@10.131.253.210 << EOF\n' +
    'version\n' +
    'EOF',
  'sshpass -p admin ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ConnectTimeout=7 admin@10.131.253.21 << EOF\n' +
    'version\n' +
    'EOF',
  'sshpass -p admin ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o ConnectTimeout=7 admin@10.131.253.211 << EOF\n' +
    'version\n' +
    'EOF'
]_
```

**Comment by gustavohenke** [comment]
Hi, thanks for reporting! A fix will be coming right up.
