### ISSUE TITLE
rxjs: executing a cancelled action

### ISSUE THREAD

**Issue by SebastienGllmt** [open-cli-tools/concurrently#518]
Concurrently worked great with my `deno` app when I was using it as a command line util

However, recently for my project I had to move to use `concurrently` from Javascript (executed by Deno) with the following code:

```typescript
import concurrently from "concurrently";
import path from "node:path";

if (import.meta.dirname == null) throw new Error("dirname is null");

const { result } = concurrently(
  [
    "deno task command1",
    "deno task command2"
  ],
  {
    killOthers: ["failure", "success"],
    cwd: path.resolve(import.meta.dirname, "../"),
    raw: true,
  },
);
```

Now this *usually* works, but occasionally I get the following error after my program ends

```typescript
error: Uncaught Error: executing a cancelled action
    at AsyncAction.execute (file:///home/git/my-project/node_modules/.deno/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:64:20)
    at AsyncScheduler.flush (file:///home/git/my-project/node_modules/.deno/rxjs@7.8.1/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:38:33)
    at cb (ext:deno_node/internal/timers.mjs:64:31)
    at callback (ext:deno_web/02_timers.js:87:7)
    at eventLoopTick (ext:core/01_core.js:210:13)
```

Versions used

```
deno 2.1.2 (stable, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
concurrently@9.1.0
```

Unfortunately, I'm not sure who is at fault here. Is it a `rxjs` bug? A `concurrently` bug? A `Deno` bug? Not sure. Given that the command-line version [runs using node](https://github.com/open-cli-tools/concurrently/blob/8d3f9761bf6269ae9abdd5dbb661314b9980d62d/bin/concurrently.ts#L1) and not Deno and so this bug only occurs when `concurrently.js` is run under Deno, I assume this is a Deno bug

I'm opening the issue here so that at least it's tracked somewhere

**Comment by SebastienGllmt** [comment]
Although I haven't tested it, it's entirely possible this was fixed by https://github.com/denoland/deno/issues/18445

**Comment by SebastienGllmt** [comment]
I can confirm the new Deno version fixed the issue (what a coincidence I ran into it 24hrs before it was fixed. Bad luck)

**Comment by gustavohenke** [comment]
Nice! 🙌 Thanks for letting us know
