### ISSUE TITLE
Group or aggregate output?

### ISSUE THREAD

**Issue by JuanCaicedo** [open-cli-tools/concurrently#75]
If you use [gnu parallel](https://www.gnu.org/software/parallel/), it has one great feature of running tasks in parallel, but grouping all of the output for a each command and printing it when that command finishes. Is there a way to do this with `concurrently`? If not, it would be a great feature 😃 

### Given these files

```bash
# script-one.sh
sleep 1
echo first
```

```bash
# script-two.sh
echo second
sleep 2
echo third
```

### Using GNU parallel
```bash
$ parallel bash ::: script-one.sh script-two.sh
first
second
third
```

### Using concurrently
```bash
$ concurrently "bash script-one.sh" "bash script-two.sh"
[1] second
[0] first
[0] bash script-one.sh exited with code 0
[1] third
[1] bash script-two.sh exited with code 0
```

**Comment by JuanCaicedo** [comment]
Wondering if anyone has any thoughts on this? I'm willing to make a PR, but want to make sure it would be a feature that would get accepted 😃

**Comment by AndrewCraswell** [comment]
This seems pretty fundamental to me. It's a big pain point to run tasks concurrently if the output can't be aggregated and instead you get hundreds or thousands of garbled output lines that you need to piece together to make sense of.

**Comment by gustavohenke** [comment]
Happy new year! This is now out in [`v7.0.0`](https://github.com/open-cli-tools/concurrently/releases/tag/v7.0.0).
